// Command genmodels generates internal/ai/base/known_models.go
// from the OpenRouter model catalog.
//
// Usage:
//
//	go run ./scripts/genmodels/main.go                 # fetch from API
//	go run ./scripts/genmodels/main.go models.json     # use local file
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"slices"
	"strings"
)

const (
	apiURL     = "https://openrouter.ai/api/v1/models"
	targetFile = "internal/ai/base/known_models.go"
)

var providers = map[string]bool{
	"openai":     true,
	"anthropic":  true,
	"google":     true,
	"deepseek":   true,
	"meta-llama": true,
	"mistralai":  true,
	"x-ai":       true,
	"qwen":       true,
	"cohere":     true,
}

type apiResponse struct {
	Data []apiModel `json:"data"`
}

type apiModel struct {
	ID              string       `json:"id"`
	ContextLen      int          `json:"context_length"`
	Architecture    architecture `json:"architecture"`
	TopProvider     topProvider  `json:"top_provider"`
	SupportedParams []string     `json:"supported_parameters"`
}

type architecture struct {
	InputModalities []string `json:"input_modalities"`
}

type topProvider struct {
	MaxCompletionTokens int `json:"max_completion_tokens"`
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "genmodels: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	data, err := loadData()
	if err != nil {
		return err
	}

	var resp apiResponse
	if err := json.Unmarshal(data, &resp); err != nil {
		return fmt.Errorf("parse JSON: %w", err)
	}

	type entry struct {
		id     string
		fields string
	}

	seen := make(map[string]bool)
	var entries []entry

	for _, m := range resp.Data {
		provider, bare, ok := strings.Cut(m.ID, "/")
		if !ok || !providers[provider] {
			continue
		}
		if strings.Contains(bare, ":") {
			continue
		}
		if seen[bare] {
			continue
		}

		ctx := m.ContextLen
		maxOut := m.TopProvider.MaxCompletionTokens
		if ctx == 0 && maxOut == 0 {
			continue
		}

		vision := slices.Contains(m.Architecture.InputModalities, "image")
		thinking := slices.Contains(m.SupportedParams, "reasoning") ||
			slices.Contains(m.SupportedParams, "include_reasoning")

		var parts []string
		if thinking {
			parts = append(parts, "Thinking: true")
		}
		if vision {
			parts = append(parts, "Vision: true")
		}
		parts = append(parts, "Streaming: true")
		if ctx > 0 {
			parts = append(parts, fmt.Sprintf("ContextWindow: %d", ctx))
		}
		if maxOut > 0 {
			parts = append(parts, fmt.Sprintf("MaxTokens: %d", maxOut))
		}

		entries = append(entries, entry{id: bare, fields: strings.Join(parts, ", ")})
		seen[bare] = true
	}

	slices.SortFunc(entries, func(a, b entry) int {
		return strings.Compare(a.id, b.id)
	})

	var b strings.Builder
	b.WriteString("// Code generated by go run ./scripts/genmodels/main.go; DO NOT EDIT.\n\n")
	b.WriteString("package base\n\n")
	b.WriteString("var knownModels = map[string]KnownModelSpec{\n")
	for _, e := range entries {
		fmt.Fprintf(&b, "\t%q: {%s},\n", e.id, e.fields)
	}
	b.WriteString("}\n")

	if err := os.WriteFile(targetFile, []byte(b.String()), 0644); err != nil {
		return err
	}
	fmt.Printf("Generated %s with %d models.\n", targetFile, len(entries))
	return nil
}

func loadData() ([]byte, error) {
	if len(os.Args) > 1 {
		fmt.Printf("Using file %s\n", os.Args[1])
		return os.ReadFile(os.Args[1])
	}
	fmt.Printf("Fetching from %s ...\n", apiURL)
	resp, err := http.Get(apiURL)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("HTTP %d", resp.StatusCode)
	}
	data, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	fmt.Printf("Downloaded %d bytes\n", len(data))
	return data, nil
}
