package engine

import (
	"time"

	"github.com/sjzar/reed/internal/bus"
	"github.com/sjzar/reed/internal/model"
	"github.com/sjzar/reed/pkg/jsonutil"
)

// Config configures a new Engine created by New.
type Config struct {
	ProcessID      string // required; generated by Manager before calling New
	PID            int    // OS process ID; set by Manager
	Mode           model.ProcessMode
	Workflow       *model.Workflow
	WorkflowSource string
	Retention      RetentionPolicy
	Bus            *bus.Bus  // required — lifecycle event publishing
	EventSink      EventSink // nil-safe — persistence subscriber
}

// Default retention values.
const (
	DefaultMaxTerminalRuns = 200
	DefaultTerminalTTL     = 30 * time.Minute
)

// RetentionPolicy controls eviction of terminal runs from memory.
type RetentionPolicy struct {
	MaxTerminalRuns int           // 0 = use default (200)
	TerminalTTL     time.Duration // 0 = use default (30min)
}

func (p RetentionPolicy) maxRuns() int {
	if p.MaxTerminalRuns > 0 {
		return p.MaxTerminalRuns
	}
	return DefaultMaxTerminalRuns
}

func (p RetentionPolicy) ttl() time.Duration {
	if p.TerminalTTL > 0 {
		return p.TerminalTTL
	}
	return DefaultTerminalTTL
}

// RunView is a read-only snapshot of a Run.
type RunView struct {
	ID             string
	ProcessID      string
	WorkflowSource string
	Status         model.RunStatus
	TriggerMeta    map[string]any
	Jobs           map[string]JobView
	Outputs        map[string]any
	ErrorCode      string
	ErrorMessage   string
	CreatedAt      time.Time
	StartedAt      time.Time
	FinishedAt     *time.Time
}

// JobView is a read-only snapshot of a Job within a RunView.
type JobView struct {
	JobID   string
	Status  model.RunStatus
	Outputs map[string]any
	Steps   map[string]StepView
}

// StepView is a read-only snapshot of a StepRun within a JobView.
type StepView struct {
	StepID       string
	StepRunID    string
	Status       model.StepStatus
	IsBackground bool
	Outputs      map[string]any
	ErrorCode    string
	ErrorMessage string
}

// deepCopy returns a fully independent copy of the RunView.
// All map and pointer fields are cloned so the caller cannot mutate the original.
func (rv RunView) deepCopy() RunView {
	cp := rv

	if rv.FinishedAt != nil {
		t := *rv.FinishedAt
		cp.FinishedAt = &t
	}
	if rv.TriggerMeta != nil {
		cp.TriggerMeta = make(map[string]any, len(rv.TriggerMeta))
		for k, v := range rv.TriggerMeta {
			cp.TriggerMeta[k] = jsonutil.DeepClone(v)
		}
	}
	if rv.Outputs != nil {
		cp.Outputs = make(map[string]any, len(rv.Outputs))
		for k, v := range rv.Outputs {
			cp.Outputs[k] = jsonutil.DeepClone(v)
		}
	}
	if rv.Jobs != nil {
		cp.Jobs = make(map[string]JobView, len(rv.Jobs))
		for jobID, jv := range rv.Jobs {
			cpJob := jv
			if jv.Outputs != nil {
				cpJob.Outputs = make(map[string]any, len(jv.Outputs))
				for k, v := range jv.Outputs {
					cpJob.Outputs[k] = jsonutil.DeepClone(v)
				}
			}
			if jv.Steps != nil {
				cpJob.Steps = make(map[string]StepView, len(jv.Steps))
				for stepID, sv := range jv.Steps {
					cpStep := sv
					if sv.Outputs != nil {
						cpStep.Outputs = make(map[string]any, len(sv.Outputs))
						for k, v := range sv.Outputs {
							cpStep.Outputs[k] = jsonutil.DeepClone(v)
						}
					}
					cpJob.Steps[stepID] = cpStep
				}
			}
			cp.Jobs[jobID] = cpJob
		}
	}
	return cp
}

// ProcessView is a read-only snapshot of a Process for status reporting.
type ProcessView struct {
	ProcessID    string
	PID          int
	Mode         model.ProcessMode
	Status       model.ProcessStatus
	CreatedAt    time.Time
	Listeners    []model.ListenerView
	ActiveRuns   []RunView
	TerminalRuns []RunView
}
